# These are supported funding model platforms

github: nusnus
open_collective: celery
patreon: # Replace with a single Patreon username
ko_fi: # Replace with a single Ko-fi username
custom: # Replace with a single custom sponsorship URL
