blank_issues_enabled: false
contact_links:
  - name: Celery Issue Tracker
    url: https://github.com/celery/celery/issues/
    about: If this issue only involves Celery, please open a new issue there.
