REDIS_FUNCTION_BACKEND = "redis_function_backend"
RABBITMQ_FUNCTION_BROKER = "rabbitmq_function_broker"
REDIS_FUNCTION_BROKER = "redis_function_broker"
REDIS_SESSION_BACKEND = "redis_session_backend"
RABBITMQ_SESSION_BROKER = "rabbitmq_session_broker"
REDIS_SESSION_BROKER = "redis_session_broker"

REDIS_IMAGE = "redis:latest"
RABBITMQ_IMAGE = "rabbitmq:latest"
REDIS_PORTS = {"6379/tcp": None}
RABBITMQ_PORTS = {"5672/tcp": None}

# Fixtures
FUNCTION_BACKENDS: list = [REDIS_FUNCTION_BACKEND]
FUNCTION_BROKERS: list = [RABBITMQ_FUNCTION_BROKER, REDIS_FUNCTION_BROKER]
SESSION_BACKENDS: list = [REDIS_SESSION_BACKEND]
SESSION_BROKERS: list = [RABBITMQ_SESSION_BROKER, REDIS_SESSION_BROKER]
CELERY_REDIS_BACKEND: str = REDIS_SESSION_BACKEND
CELERY_REDIS_BROKER: str = REDIS_SESSION_BROKER
CELERY_RABBITMQ_BROKER: str = RABBITMQ_SESSION_BROKER

# Backends
REDIS_FUNCTION_BACKEND_ENV: dict = {}
REDIS_FUNCTION_BACKEND_IMAGE: str = REDIS_IMAGE
REDIS_FUNCTION_BACKEND_PORTS: dict = REDIS_PORTS
REDIS_SESSION_BACKEND_ENV: dict = {}
REDIS_SESSION_BACKEND_IMAGE: str = REDIS_IMAGE

# Brokers
REDIS_SESSION_BACKEND_PORTS: dict = REDIS_PORTS
RABBITMQ_FUNCTION_BROKER_ENV: dict = {}
RABBITMQ_FUNCTION_BROKER_IMAGE: str = RABBITMQ_IMAGE
RABBITMQ_FUNCTION_BROKER_PORTS: dict = RABBITMQ_PORTS
RABBITMQ_SESSION_BROKER_ENV: dict = {}
RABBITMQ_SESSION_BROKER_IMAGE: str = RABBITMQ_IMAGE
RABBITMQ_SESSION_BROKER_PORTS: dict = RABBITMQ_PORTS
REDIS_FUNCTION_BROKER_ENV: dict = {}
REDIS_FUNCTION_BROKER_IMAGE: str = REDIS_IMAGE
REDIS_FUNCTION_BROKER_PORTS: dict = REDIS_PORTS
REDIS_SESSION_BROKER_ENV: dict = {}
REDIS_SESSION_BROKER_IMAGE: str = REDIS_IMAGE
REDIS_SESSION_BROKER_PORTS: dict = REDIS_PORTS
